version: '3'

services:
  db:
    image: postgres
    
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate_schemas && python manage.py runserver 0.0.0.0:8000"
    container_name: bitpoint
    volumes:
      - .:/bitpoint
    ports:
      - "8000:8000"
    depends_on:
      - db